use_frameworks!

workspace 'sdk'

def sdk_pods
    pod 'SSZipArchive'
end

def networking_pods
    podspec :path => '../networking/networking.podspec'
    pod "PromiseKit", "~> 6.8"
end

target 'sdk' do
    project '../sdk/sdk.xcodeproj'
    sdk_pods
    networking_pods
end

target 'networkingTests' do
    networking_pods
end

target 'networking' do
    project '../networking/networking.xcodeproj'
    networking_pods
end
