use_frameworks!

platform :ios, '11.0'
workspace '../sdk'

def sdk_pods
  pod 'SSZipArchive'
end

def networking_pods
  podspec :path => '../networking/networking.podspec'
end

target 'sdk' do
  project '../sdk/sdk.xcodeproj'
  sdk_pods
  networking_pods
  target 'sdkTests'
end

target 'networking' do
  project '../networking/networking.xcodeproj'
  networking_pods
  target 'networkingTests'
end
