use_frameworks!

platform :ios, '11.0'
workspace '../sdk'

target 'VCUseCase' do
  project '../VCUseCase/VCUseCase.xcodeproj'
  pod 'PromiseKit'
  target 'VCUseCaseTests'
end

target 'VCRepository' do
  project '../VCRepository/VCRepository.xcodeproj'
  pod 'PromiseKit'
  target 'VCRepositoryTests'
end

target 'VCNetworking' do
  project '../VCNetworking/VCNetworking.xcodeproj'
  pod 'PromiseKit'
  target 'VCNetworkingTests'
end

target 'VCCrypto' do
  project '../VCCrypto/VCCrypto.xcodeproj'
  pod 'secp256k1_ios'
  target 'VCCryptoTests'
end
