use_frameworks!

platform :ios, '11.0'
workspace '../sdk'

def serialization_pods
  podspec :path => '../VCSerialization/VCSerialization.podspec'
end

def networking_pods
  podspec :path => '../VCNetworking/VCNetworking.podspec'
end

def vcjwt_pods
    podspec :path => '../VcJwt/VcJwt.podspec'
end

def vccrypto_pods
  podspec :path => '../VCCrypto/VcCrypto.podspec'
end

target 'sdk' do
  project '../sdk/sdk.xcodeproj'
  pod 'VCNetworking', path: '../VCNetworking'
  pod 'VCSerialization', path: '../VCSerialization'
  target 'sdkTests'
end

target 'VCNetworking' do
  project '../VCNetworking/VCNetworking.xcodeproj'
  pod 'VCSerialization', path: '../VCSerialization'
  networking_pods
  target 'VCNetworkingTests'
end

target 'VCSerialization' do
  project '../VCSerialization/VCSerialization.xcodeproj'
  pod 'VcJwt', path: '../VcJwt'
  serialization_pods
  target 'VCSerializationTests'
end

target 'VcCrypto' do
  project '../VCCrypto/VcCrypto.xcodeproj'
  vccrypto_pods
  target 'VcCryptoTests'
end

target 'VcJwt' do
  project '../VcJwt/VcJwt.xcodeproj'
  pod 'VcCrypto', path: '../VCCrypto'
  vcjwt_pods
  target 'VcJwtTests'
end
